from dataclasses import dataclass

import numpy as np
import uaibot as ub


@dataclass(frozen=True)
class VectorFieldConfig:
    kt1: float = 12.3
    kt2: float = 0.3
    kt3: float = 1.0
    kn1: float = 0.10
    kn2: float = 0.04
    ds: float = 0.085
    delta: float = 1e-2


def vector_field_twist(
    state_htm: np.ndarray,
    htm_path,
    config: VectorFieldConfig,
) -> tuple[np.ndarray, float, int]:
    """Return the nominal spatial twist generated by the SE(3) vector field."""
    twist, _, _, distance, index = ub.Robot.vector_field_SE3(
        state=state_htm,
        curve=htm_path,
        kt1=config.kt1,
        kt2=config.kt2,
        kt3=config.kt3,
        kn1=config.kn1,
        kn2=config.kn2,
        ds=config.ds,
        delta=config.delta,
    )

    twist = np.asarray(twist, dtype=float).reshape(6, 1)
    position = np.asarray(state_htm, dtype=float)[:3, 3].reshape(3, 1)

    # Keep the same spatial-twist conversion used in the original code.
    twist[:3] += np.asarray(ub.Utils.S(twist[3:6]), dtype=float) @ position

    return twist, float(distance), int(index)


def pose_regulation_twist(
    H: np.ndarray,
    H_target: np.ndarray,
    gain: float = 0.5,
) -> tuple[np.ndarray, np.ndarray]:
    """First-order counterpart of the original final-pose controller."""

    def diag_as_column(M: np.ndarray) -> np.ndarray:
        return np.diag(M).reshape(3, 1)

    H = np.asarray(H, dtype=float).reshape(4, 4)
    H_target = np.asarray(H_target, dtype=float).reshape(4, 4)

    position = H[:3, 3].reshape(3, 1)
    position_target = H_target[:3, 3].reshape(3, 1)
    rotation = H[:3, :3]
    rotation_target = H_target[:3, :3]

    Sx = np.asarray(ub.Utils.S([1, 0, 0]), dtype=float)
    Sy = np.asarray(ub.Utils.S([0, 1, 0]), dtype=float)
    Sz = np.asarray(ub.Utils.S([0, 0, 1]), dtype=float)

    error = np.zeros((6, 1))
    error[:3] = position - position_target
    error[3:6] = diag_as_column(np.eye(3) - rotation_target.T @ rotation)

    error_jacobian = np.zeros((6, 6))
    error_jacobian[:3, :3] = np.eye(3)

    ax = diag_as_column(-rotation_target.T @ Sx @ rotation)
    ay = diag_as_column(-rotation_target.T @ Sy @ rotation)
    az = diag_as_column(-rotation_target.T @ Sz @ rotation)
    error_jacobian[3:6, 3:6] = np.hstack((ax, ay, az))

    # r_dot = D_r * xi. Choose xi so r_dot = -gain * r.
    nominal_twist = np.asarray(
        ub.Utils.dp_inv(np.matrix(error_jacobian)), dtype=float
    ) @ (-gain * error)
    return nominal_twist.reshape(6, 1), error
